./spl ../MyLabs/Lab16_assignments/timer_interrupt.spl
./spl ../MyLabs/Lab16_assignments/read_interrupt_int6.spl
./spl ../MyLabs/Lab16_assignments/write_interrupt_int7.spl
./spl ../MyLabs/Lab16_assignments/device_manager_module4.spl
./spl ../MyLabs/Lab16_assignments/resource_manager_module0.spl
./spl ../MyLabs/Lab16_assignments/boot_module.spl
./spl ../MyLabs/Lab16_assignments/scheduler_module5.spl
./spl ../MyLabs/Lab16_assignments/os_startup.spl
./spl ../MyLabs/Lab16_assignments/int10_module.spl
./spl ../MyLabs/Lab16_assignments/console_interrupt_handler.spl