./spl ../MyLabs/Lab21/timer_interrupt.spl
./spl ../MyLabs/Lab21/read_interrupt_int6.spl
./spl ../MyLabs/Lab21/write_interrupt_int7.spl
./spl ../MyLabs/Lab21/device_manager_module4.spl
./spl ../MyLabs/Lab21/resource_manager_module0.spl
./spl ../MyLabs/Lab21/boot_module.spl
./spl ../MyLabs/Lab21/scheduler_module5.spl
./spl ../MyLabs/Lab21/os_startup.spl
./spl ../MyLabs/Lab21/int10_module.spl
./spl ../MyLabs/Lab21/console_interrupt_handler.spl
./spl ../MyLabs/Lab21/process_manager_module1.spl
./spl ../MyLabs/Lab21/memory_manager_module2.spl
./spl ../MyLabs/Lab21/exec_interrupt9.spl
./spl ../MyLabs/Lab21/disk_interrupt_handler.spl
./spl ../MyLabs/Lab21/exhandler.spl
./spl ../MyLabs/Lab21/fork_int8.spl
./spl ../MyLabs/Lab21/shutdown_interrupt15.spl
./spl ../MyLabs/Lab21/interrupt11.spl