./spl ../MyLabs/Lab24/timer_interrupt.spl
./spl ../MyLabs/Lab24/read_interrupt_int6.spl
./spl ../MyLabs/Lab24/write_interrupt_int7.spl
./spl ../MyLabs/Lab24/device_manager_module4.spl
./spl ../MyLabs/Lab24/resource_manager_module0.spl
./spl ../MyLabs/Lab24/boot_module.spl
./spl ../MyLabs/Lab24/scheduler_module5.spl
./spl ../MyLabs/Lab24/os_startup.spl
./spl ../MyLabs/Lab24/int10_module.spl
./spl ../MyLabs/Lab24/console_interrupt_handler.spl
./spl ../MyLabs/Lab24/process_manager_module1.spl
./spl ../MyLabs/Lab24/memory_manager_module2.spl
./spl ../MyLabs/Lab24/exec_interrupt9.spl
./spl ../MyLabs/Lab24/disk_interrupt_handler.spl
./spl ../MyLabs/Lab24/exhandler.spl
./spl ../MyLabs/Lab24/fork_int8.spl
./spl ../MyLabs/Lab24/shutdown_interrupt15.spl
./spl ../MyLabs/Lab24/interrupt11.spl
./spl ../MyLabs/Lab24/int4_file_system.spl
./spl ../MyLabs/Lab24/interrupt5.spl
./spl ../MyLabs/Lab24/file_manager_module3.spl
./spl ../MyLabs/Lab24/interrupt13.spl
./spl ../MyLabs/Lab24/interrupt14.spl