./spl ../MyLabs/Lab23/timer_interrupt.spl
./spl ../MyLabs/Lab23/read_interrupt_int6.spl
./spl ../MyLabs/Lab23/write_interrupt_int7.spl
./spl ../MyLabs/Lab23/device_manager_module4.spl
./spl ../MyLabs/Lab23/resource_manager_module0.spl
./spl ../MyLabs/Lab23/boot_module.spl
./spl ../MyLabs/Lab23/scheduler_module5.spl
./spl ../MyLabs/Lab23/os_startup.spl
./spl ../MyLabs/Lab23/int10_module.spl
./spl ../MyLabs/Lab23/console_interrupt_handler.spl
./spl ../MyLabs/Lab23/process_manager_module1.spl
./spl ../MyLabs/Lab23/memory_manager_module2.spl
./spl ../MyLabs/Lab23/exec_interrupt9.spl
./spl ../MyLabs/Lab23/disk_interrupt_handler.spl
./spl ../MyLabs/Lab23/exhandler.spl
./spl ../MyLabs/Lab23/fork_int8.spl
./spl ../MyLabs/Lab23/shutdown_interrupt15.spl
./spl ../MyLabs/Lab23/interrupt11.spl
./spl ../MyLabs/Lab23/int4_file_system.spl